services:
  - type: web
    name: car-rental-backend
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: mongoDb
        sync: false
      - key: FRONTEND_URL
        sync: false 